import type { EmailValidationProviderId, EmailValidationStatus } from "./email-validation";

export type PhoneDiscoveryMethod =
  | "tel_href"
  | "labeled_text"
  | "serp_result"
  | "website_plain";

export type PhoneConfidence = "high" | "medium" | "low";

export type LeadSourceKind =
  | "serpapi"
  | "autonomous"
  | "google-custom"
  | "mock"
  | "import"
  | "unknown";

export type EmailDiscoveryMethod =
  | "website_home"
  | "website_contact"
  | "website_footer"
  | "website_about"
  | "website_team"
  | "serp_result"
  | "external_provider";

export type LocationMatch =
  | "verified"
  | "likely"
  | "unknown"
  | "outside_target";

export type EmailQualityClass =
  | "VALID_CONFIRMED"
  | "VALID_MX_UNVERIFIED"
  | "UNKNOWN"
  | "INVALID_SYNTAX"
  | "DOMAIN_NOT_FOUND"
  | "NO_MX"
  | "GUESS_NOT_VERIFIED"
  | "NO_EMAIL";

export interface Lead {
  id: string;
  company: string;
  website: string;
  email: string | null;
  phone: string;
  address: string;
  category: string;
  aiScore: number;
  /** Search/handoff batch this lead belongs to (never mix without explicit action). */
  batchId?: string;
  /** Per-file import batch — campaign membership uses only the current upload. */
  importBatchId?: string;
  savedAt?: string;
  emailValidationStatus?: EmailValidationStatus;
  emailValidationReason?: string;
  normalizedEmail?: string;
  emailValidatedAt?: string;
  emailValidationProvider?: EmailValidationProviderId;
  emailDomain?: string;
  hasMxRecords?: boolean;
  isRoleBasedEmail?: boolean;
  enrichmentStatus?: "pending" | "running" | "completed" | "failed" | "skipped";
  enrichmentError?: string;
  scoringStatus?: "pending" | "running" | "completed" | "failed";
  scoringError?: string;
  lastProcessedAt?: string;
  /** True when the row was generated by mock/padding. Forbidden in real search. */
  synthetic?: boolean;
  syntheticReason?: string;
  sourceKind?: LeadSourceKind;
  emailSourceUrl?: string | null;
  emailSourceType?: EmailDiscoveryMethod | null;
  emailDiscoveryMethod?: EmailDiscoveryMethod | null;
  emailFoundAt?: string | null;
  emailIsGuessed?: boolean;
  phoneSourceUrl?: string | null;
  phoneFoundAt?: string | null;
  phoneRaw?: string | null;
  phoneDiscoveryMethod?: PhoneDiscoveryMethod | null;
  phoneConfidence?: PhoneConfidence | null;
  latitude?: number | null;
  longitude?: number | null;
  requestedLocation?: string;
  discoveredAddress?: string;
  postcode?: string | null;
  locationMatch?: LocationMatch;
}

export interface SearchRecord {
  id: string;
  keyword: string;
  location: string;
  resultsCount: number;
  date: string;
  leads?: Lead[];
  batchId?: string;
}

export interface DashboardStats {
  companiesFound: number;
  validEmails: number;
  conversionRate: number;
  leadsToday: number;
}

export function leadFingerprint(lead: Pick<Lead, "company" | "website">) {
  return `${lead.company.toLowerCase()}|${lead.website.toLowerCase()}`;
}
